name: cincailah
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1




environment:
  sdk: ^3.9.0

dependencies:
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  just_audio: ^0.9.39
  audio_session: ^0.1.21

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0


  device_calendar: ^4.3.3
  table_calendar: ^3.2.0

  #  Google Calendar API
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0

  # HTTP
  http: ^1.2.2

  # Profile
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - audio/
