// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI0fnlsyqMoOETqq1IOokZHAHRNHTnggA',
    appId: '1:1064076803852:web:f6d4813b82c5ec992a9329',
    messagingSenderId: '1064076803852',
    projectId: 'codenection-cincailah-53ce0',
    authDomain: 'codenection-cincailah-53ce0.firebaseapp.com',
    storageBucket: 'codenection-cincailah-53ce0.firebasestorage.app',
    measurementId: 'G-1TZD74WMHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvn_OgifXipnf3DnJkznTHfNpN5-n85vY',
    appId: '1:1064076803852:android:c185fd3cc17ef4202a9329',
    messagingSenderId: '1064076803852',
    projectId: 'codenection-cincailah-53ce0',
    storageBucket: 'codenection-cincailah-53ce0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACvvl4QibllqZai7GapzIVlB6DEDgnM08',
    appId: '1:1064076803852:ios:2e6d7df3f2aff19e2a9329',
    messagingSenderId: '1064076803852',
    projectId: 'codenection-cincailah-53ce0',
    storageBucket: 'codenection-cincailah-53ce0.firebasestorage.app',
    iosBundleId: 'com.example.cincailah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACvvl4QibllqZai7GapzIVlB6DEDgnM08',
    appId: '1:1064076803852:ios:2e6d7df3f2aff19e2a9329',
    messagingSenderId: '1064076803852',
    projectId: 'codenection-cincailah-53ce0',
    storageBucket: 'codenection-cincailah-53ce0.firebasestorage.app',
    iosBundleId: 'com.example.cincailah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI0fnlsyqMoOETqq1IOokZHAHRNHTnggA',
    appId: '1:1064076803852:web:fd495c0a601dd3df2a9329',
    messagingSenderId: '1064076803852',
    projectId: 'codenection-cincailah-53ce0',
    authDomain: 'codenection-cincailah-53ce0.firebaseapp.com',
    storageBucket: 'codenection-cincailah-53ce0.firebasestorage.app',
    measurementId: 'G-BEE94SC802',
  );

}